version: "3.6"

services:

# Nginx Container

  nginx:
    build: ./requirements/nginx/
    image: nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/wordpress
    ports:
    - "443:443"
    - "80:80"
    networks:
      - inception

# Wordpress Container

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/wordpress/
    ports:
    - "9000:9000"
    env_file:
        - .env
    networks:
      - inception

# Mariadb Container

  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql/
    ports:
    - "3306:3306"
    env_file:
        - .env
    networks:
      - inception

# Adminer container

  adminer:
    build: requirements/bonus/adminer
    image: adminer
    container_name: adminer
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - inception
    ports:
      - "8080:8080"

# Static Website container

  website:
    build: requirements/bonus/website
    image: website
    container_name: website
    restart: unless-stopped
    ports:
      - "1337:80"
    networks:
      - inception

# cadvisor container

  cadvisor:
    build: requirements/bonus/cadvisor
    image: cadvisor
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
        - inception
    ports:
      - "7000:7000"

# Network

networks:
  inception:
    name: inception
    driver: bridge

# volumes

volumes:
  wordpress:
    driver: local 
    driver_opts:
      type: none 
      device: /home/oagrram/data/wordpress
      o: bind

  mariadb:
    driver: local 
    driver_opts:
      type: none 
      device: /home/oagrram/data/mariadb
      o: bind
