version: "3.6"

services:

mariadb:
  build: .
  container_name: mariadb
  networks:
    - network
  volumes:
    - /home/oagrram/data/dbdata:/var/lib/mysql
  ports:
   - "3306:3306"


wordpress:
  build: .
  container_name: wordpress
  networks:
    - network
  volumes:
    - /home/oagrram/data/wordpress:/var/www/wordpress
  ports:
   - "9000:9000"


nginx:
  build: .
  container_name: nginx
  networks: 
    - network
  volumes:
    - /home/oagrram/data/wordpress:/var/www/wordpress
  ports:
   - "443:443"

networks:
  network:
    name: wp-network
    driver: bridge
