version: "3.6"
services:
 wordpress:
  build: .
  container_name: wordpress
  networks:
    - network
  volumes:
    - /home/oagrram/data/wordpress:/var/www/wordpress
  ports:
   - "9000:9000"
networks:
  network:
    name: wp-network
    driver: bridge