version: "3.6"
services:
 nginx:
  build: .
  networks: 
    - network
  volumes:
    - /home/oagrram/data/wordpress:/var/www/wordpress
  ports:
   - "443:443"
networks:
  network:
    name: wp_network 
    driver: bridge

