version: '3'
services:
  wordpress:
    image: wordpress:6.0.2-php8.1-fpm
    environment:
      - WORDPRESS_DB_NAME=wpdb
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_PASSWORD=aqwe123
    container_name: wordpress1
    networks:   
      - network
    volumes:
      - /home/oagrram/data/wordpress:/var/www/wordpress
    ports:
    - "9000:9000"
networks:
  network:
    name: wp_network 
    driver: bridge


