version: "3.6"
services:
 mariadb:
  build: .
  container_name: mariadb
  networks:
    - network
  volumes:
    - /home/oagrram/data/dbdata:/var/lib/mysql
  ports:
   - "3306:3306"
networks:
  network:
    name: wp-network
    driver: bridge
